version: "3"
services:
  api:
    image: registry:5000/ch04/todoapi:latest
    deploy:
      replicas: 2
    environment:
      TODO_BIND: ":8080"
      TODO_MASTER_URL: "gihyo@tcp(todo_mysql_master:3306)/tododb?parseTime=tru"
      TODO_SLAVE_URL: "gihyo@tcp(todo_mysql_slave:3306)/tododb?parseTime=tru"
    networks:
      - todoapp

networks:
  todoapp:
    external: true